version: '3.7'

services:

  demo_db:
    container_name: demo_db
    image: postgres:9.6-alpine
    command: postgres -c max_connections=1000
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=demo
      - POSTGRES_DB=demo
    volumes:
      - pgsql-data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - mode: host
        protocol: tcp
        published: 5432
        target: 5432

volumes:
  pgsql-data:
    name: pgsql-data
