/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.7).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package virtu.systems.demo.api;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import virtu.systems.demo.api.dto.CalculateInsurancePremiumRequestDto;
import virtu.systems.demo.api.dto.CalculateInsurancePremiumResponseDto;

import javax.validation.Valid;

@Api(value = "Calculate", description = "the Calculate API")
public interface CalculateApi {

    @ApiOperation(value = "calculate insurance premium", nickname = "calculateInsurancePremium", notes = "Список типов недвижимости", response = CalculateInsurancePremiumResponseDto.class, tags={ "Calculate", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CalculateInsurancePremiumResponseDto.class) })
    @RequestMapping(value = "/calculate",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<CalculateInsurancePremiumResponseDto> calculateInsurancePremium(@ApiParam(value = "" ,required=true )  @Valid @RequestBody CalculateInsurancePremiumRequestDto data);

}
