/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.7).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package virtu.systems.demo.api;

import virtu.systems.demo.api.dto.RealEstateTypesResponseDto;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Optional;

@Api(value = "RealEstate", description = "the RealEstate API")
public interface RealEstateApi {

    @ApiOperation(value = "type list", nickname = "getRealEstateTypes", notes = "Список типов недвижимости", response = RealEstateTypesResponseDto.class, tags={ "RealEstate", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = RealEstateTypesResponseDto.class) })
    @RequestMapping(value = "/realEstate/types",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<RealEstateTypesResponseDto> getRealEstateTypes();

}
